### ISSUE TITLE
Connection timed out after not receiving any message for 10000ms. Disconnecting.

### ISSUE THREAD

**Issue by mankjon** [PlayFab/MpsSamples#49] opened 2021-11-18 08:10 UTC
I set Deplay server at multipaler tab and test at UnityClient but it time out every time.
How to fix this issue.

KCP: Connection timed out after not receiving any message for 10000ms. Disconnecting.
UnityEngine.Debug:LogWarning (object)
kcp2k.KcpConnection:HandleTimeout (uint) (at Assets/Mirror/Runtime/Transport/KCP/kcp2k/highlevel/KcpConnection.cs:154)
kcp2k.KcpConnection:TickIncoming_Connected (uint) (at Assets/Mirror/Runtime/Transport/KCP/kcp2k/highlevel/KcpConnection.cs:250)
kcp2k.KcpConnection:TickIncoming () (at Assets/Mirror/Runtime/Transport/KCP/kcp2k/highlevel/KcpConnection.cs:362)
kcp2k.KcpClient:TickIncoming () (at Assets/Mirror/Runtime/Transport/KCP/kcp2k/highlevel/KcpClient.cs:89)
kcp2k.KcpTransport:ClientEarlyUpdate () (at Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs:117)
Mirror.NetworkClient:NetworkEarlyUpdate () (at Assets/Mirror/Runtime/NetworkClient.cs:1198)
Mirror.NetworkLoop:NetworkEarlyUpdate () (at Assets/Mirror/Runtime/NetworkLoop.cs:182)

**Comment by dgkanatsios** [comment] 2021-11-18 16:41
have you configured your ports correctly?

**Comment by mankjon** [comment] 2021-11-19 07:53
> have you configured your ports correctly?

Yes, I configured my port correctly.
I use port 30000 at kcpTransport.
I get port from Playfab->MultiPlayer->Servers

Can I config more?

**Comment by roestzwiee** [comment] 2021-11-19 23:13
Have a look at this  #47 

Is it possible you changed the server or client scene?

**Comment by mankjon** [comment] 2021-11-23 06:08
> 

I change client scene.

**Comment by roestzwiee** [comment] 2021-11-23 11:37
Read the NetworkManager docs. Specifically Scene Management. Scenes have to be the same.

**Comment by dgkanatsios** [comment] 2022-01-21 04:56
Closing, please feel free to re-open if the issue is not resolved. Thanks!

**Closed by dgkanatsios** 2022-01-21 04:56 UTC
